"""initial schema

Revision ID: 6f253a5df2e9
Revises: 
Create Date: 2026-09-25 22:22:51.785503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '6f253a5df2e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("username", sa.String(200), nullable=False),
        sa.Column("password_hash", sa.String(300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.text("now()"),
        ),
        sa.PrimaryKeyConstraint("id", name="users_pkey"),
    )
    op.create_index("ix_users_username", "users", ["username"], unique=True)

    op.create_table(
        "claims",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("claim_id", sa.String(), nullable=False),
        sa.Column("policy_number", sa.String(), nullable=False),
        sa.Column("claim_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("owner_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["owner_id"], ["users.id"], name="claims_owner_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="claims_pkey"),
    )
    op.create_index("ix_claims_claim_id", "claims", ["claim_id"], unique=True)
    op.create_index("ix_claims_owner_id", "claims", ["owner_id"], unique=False)
    op.create_index("ix_claims_policy_number", "claims", ["policy_number"], unique=False)

    op.create_table(
        "conversations",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("user_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("session_id", sa.String(128), nullable=False),
        sa.Column("title", sa.String(255), nullable=False, server_default=sa.text("'New Chat'::character varying")),
        sa.Column("messages", postgresql.JSONB(), nullable=False, server_default=sa.text("'[]'::jsonb")),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.text("now()")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="conversations_user_id_fkey", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name="conversations_pkey"),
    )
    op.create_index("ix_conversations_session_id", "conversations", ["session_id"], unique=True)

    op.create_table(
        "policy_chunks",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("chunk_id", sa.String(128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("section", sa.String(255), nullable=False),
        sa.Column("source", sa.String(255), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("sub_chunk_index", sa.Integer(), nullable=False),
        sa.Column("tsvector", postgresql.TSVECTOR(), nullable=False),
        sa.PrimaryKeyConstraint("id", name="policy_chunks_pkey"),
    )
    op.create_index("ix_policy_chunks_chunk_id", "policy_chunks", ["chunk_id"], unique=True)
    op.create_index("ix_policy_chunks_section", "policy_chunks", ["section"], unique=False)
    op.create_index(
        "ix_policy_chunks_tsvector",
        "policy_chunks",
        ["tsvector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_policy_chunks_tsvector", table_name="policy_chunks", postgresql_using="gin")
    op.drop_index("ix_policy_chunks_section", table_name="policy_chunks")
    op.drop_index("ix_policy_chunks_chunk_id", table_name="policy_chunks")
    op.drop_table("policy_chunks")
    op.drop_index("ix_conversations_session_id", table_name="conversations")
    op.drop_table("conversations")
    op.drop_index("ix_claims_policy_number", table_name="claims")
    op.drop_index("ix_claims_owner_id", table_name="claims")
    op.drop_index("ix_claims_claim_id", table_name="claims")
    op.drop_table("claims")
    op.drop_index("ix_users_username", table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
